### ISSUE TITLE
Add Heap sort algorihtm to the visualizer.

### ISSUE THREAD

**Issue by anubhavitis** [servermonk/Algorithm-Visualizer#10]
**Description**
In the sorting algorithm page, the Heap Sort algorithm is missing. Add proper algorithms there.

**The solution to be accepted**
1.) In Heap_sort.js, Complete function selection(divs, height) with appropriate use for the functions provided.
2.) Used the same colors to fill up the division as used in bubble_sort.js.
3.) The visualizer is working properly for selection sorting.

**Additional context**
Use Bubble_sort.js for reference.
*NOTE*: We're not accepting any changes in the `master` branch, make PRs in the `beta` branch only.

**Comment by esla-ahme** [comment]
Hi @anubhavitis I am interested in fixing this issue kindely assign it to me. 
By the way I noticed strange behaviour when opened the website on my android mobile and it seemed no showing the graph till I refresh or leave the page it shows for a moment then the page is reloded or the new page is loaded 
![Screenshot_20201003-035435_Chrome](https://user-images.githubusercontent.com/36511729/94980733-d7135380-052c-11eb-84c3-0c8de1a524fe.jpg)
