### ISSUE TITLE
Reload Button clears the bars to be sorted

### ISSUE THREAD

**Issue by Jh123x** [servermonk/Algorithm-Visualizer#24]
**Describe the bug**
The reload buttons clear the bars to be sorted by the sorting algorithm

**To Reproduce**
1. Go to [Algorithm Visualizer page](https://vizalgo.netlify.app/public/sorting/sorting_page.html)
2. Click on reload

**Expected behavior**
1. The bars reset into random order.

**Screenshots**
![image](https://user-images.githubusercontent.com/10459011/100534512-a01a9f00-324a-11eb-9ddf-e34c0ba5fca8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser: Chrome
 - Version: Latest

**Comment by anubhavitis** [comment]
Thanks for letting us know. We'll look forward to fixing it.
