### ISSUE TITLE
DFS and BFS not working

### ISSUE THREAD

**Issue by forhadkhan** [servermonk/Algorithm-Visualizer#25]
**Describe the bug**

**To Reproduce**
1. Go to: https://vizalgo.netlify.app/
2. Click on: Path Algorithms
3. Scroll down to 'BFS' or 'DFS' from Path Algorithm
4. Click 'START'
5. See error

**Expected behavior**
It should visualize DFS/BFS like A* 

**Desktop :**
 - OS: Win10
 - Browser: Chrome
 - Version: 87.0.4280.66

**Comment by anubhavitis** [comment]
Yes, DFS and BFS codes are not yet added.
Will do it soon enough.

**Comment by anubhavitis** [comment]
It's working now. Thanks for letting us know.
