### ISSUE TITLE
Design a better homepage for the app.

### ISSUE THREAD

**Issue by ayush-tiwari57** [servermonk/Algorithm-Visualizer#4]
**Is your feature request related to a problem? Please describe.**
Make a better main page than the current one.

**Describe the solution you'd like**
The page must contain the logo and two cards:
 - one for graph algorithms which will direct to the Graph Algorithms page
 - one for sorting algorithms which will direct to the Sorting Algorithms page

**ScreenShots**
The current main page looks like this:
![Screenshot (169)](https://user-images.githubusercontent.com/47775419/94728620-2404f780-037e-11eb-846f-869522b79040.png)
![Screenshot (170)](https://user-images.githubusercontent.com/47775419/94728688-3717c780-037e-11eb-829c-21fd20c7d6f4.png)

**Additional context**
*NOTE*: We're not accepting any changes in the `master` branch, make PRs in the `beta` branch only.

**Comment by STM3900** [comment]
I'm working on it !

**Comment by ayush-tiwari57** [comment]
ok then @STM3900 , I will be assigning this issue to you. All the best and do give us a star if you like our project
