### ISSUE TITLE
Add Selection Sort algorithm to the sorting visualizer

### ISSUE THREAD

**Issue by anubhavitis** [servermonk/Algorithm-Visualizer#6]
**Description**
In the sorting algorithm page, the Selection Sort algorithm is missing. Add proper algorithms there.

**Solution to be accepted**
1.) In selection_sort.js, Complete function `selection(divs, height)` with appropriate use for the functions provided.
2.) Used the same colors to fill up the division as used in bubble_sort.js.
3.) The visualizer is working properly for selection sorting.

**Additional context**
Use Bubble_sort.js for reference.
*NOTE*: We're not accepting any changes in the `master` branch, make PRs in the `beta` branch only.

**Comment by KonradLinkowski** [comment]
I can do this, but I looked at the code and I have to ask if there is any specific reason to use `var` and `function`.

**Comment by mallikarjun2000** [comment]
Hey!
I would like to work on this issue. can you assign it to me?

**Comment by mallikarjun2000** [comment]
Is this issue still open to work on? can you please tell me?

**Comment by anubhavitis** [comment]
yes, it's open.

**Comment by mallikarjun2000** [comment]
Please assign it to me I would like to work on this issue.

**Comment by anubhavitis** [comment]
All the best bro.
