### ISSUE TITLE
Add Insertion Sort algorithm to the visualizer.

### ISSUE THREAD

**Issue by anubhavitis** [servermonk/Algorithm-Visualizer#7]
**Description**
In the sorting algorithm page, the Insertion Sort algorithm is missing. Add proper algorithms there.

**Solution to be accepted**
1.) In Insertion_sort.js, Complete function `selection(divs, height)` with appropriate use for the functions provided.
2.) Used the same colors to fill up the division as used in bubble_sort.js.
3.) The visualizer is working properly for selection sorting.

**Additional context**
Use Bubble_sort.js for reference.
*NOTE*: We're not accepting any changes in the `master` branch, make PRs in the `beta` branch only.

**Comment by vandana1499** [comment]
I have worked on this issue.

**Comment by ayush-tiwari57** [comment]
@vandana1499 thanx for contributing, we will review your PR and get back to you

**Comment by vandana1499** [comment]
May I know the problem with my code?

**Comment by anubhavitis** [comment]
Sure.
The insertion sort fucntion that you completed wasn't working as expected. As of what I think is, you weren't well versed with our implementation model, you might have messed up somewhere in divs[] array. Also, color update function was not placed appropriately.

**Comment by anubhavitis** [comment]
Issue is still open, so if you are still interested to contribute, then you are always welcome. If you need any help, just put it here, or on our slack channal.

**Comment by mohilkhare1708** [comment]
I would like to work on it. Can it be assigned to me?
@anubhavitis 
@servermonk

**Comment by anubhavitis** [comment]
Sure, lemme do it.

**Comment by anubhavitis** [comment]
@mohilkhare1708, Any updates on the issue??

**Comment by mohilkhare1708** [comment]
@anubhavitis I have started working on it today. I had to halt due to exams, I'll let you know about the progress from today.
