### ISSUE TITLE
Add Merge sort algorithm to the visualizer.

### ISSUE THREAD

**Issue by anubhavitis** [servermonk/Algorithm-Visualizer#8]
**Description**
In the sorting algorithm page, the Merge Sort algorithm is missing. Add proper algorithms there.

**The solution to be accepted**
1.) In Merge_sort.js, Complete function selection(divs, height) with appropriate use for the functions provided.
2.) Used the same colors to fill up the division as used in bubble_sort.js.
3.) The visualizer is working properly for selection sorting.

**Additional context**
Use Bubble_sort.js for reference.
*NOTE*: We're not accepting any changes in the `master` branch, make PRs in the `beta` branch only.

**Comment by krishnmohan19** [comment]
hey @anubhavitis 
can i work on this.

**Comment by ayush-tiwari57** [comment]
hey @krishnmohan19 I have assigned this issue to you so you can start working on it

**Comment by krishnmohan19** [comment]
yes @servermonk .
i am stuck with my code. not able to use color combination. help me out

**Comment by anubhavitis** [comment]
Sure, So the color combination required is
1.) Red: while doing the partition,
2.) Green: while merging the partition,
3.) Yellow: for current active div.

Is this what you wanted to know?
