### ISSUE TITLE
Add Quick sort algorithm to the visualizer.

### ISSUE THREAD

**Issue by anubhavitis** [servermonk/Algorithm-Visualizer#9]
**Description**
In the sorting algorithm page, the Quick Sort algorithm is missing. Add proper algorithms there.

**The solution to be accepted**
1.) In Quick_sort.js, Complete function selection(divs, height) with appropriate use for the functions provided.
2.) Used the same colors to fill up the division as used in bubble_sort.js.
3.) The visualizer is working properly for selection sorting.

**Additional context**
Use Bubble_sort.js for reference.
*NOTE*: We're not accepting any changes in the `master` branch, make PRs in the `beta` branch only.

**Comment by mallikarjun2000** [comment]
Hey!,
I would like to take this issue and work on it. can you please assign it to me?

**Comment by ayush-tiwari57** [comment]
sure @mallikarjun2000 , I have assigned this task to you so could start working on it. All the Best
